/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.stagiaires;

import java.awt.Image;
import java.io.IOException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author medam
 */
public class Interface extends javax.swing.JFrame {

    private DefaultTableModel dt; //tableau telque les enregistrements est par défaut sous forme de matrice lignes et colonnes
    private int id;
    private String nom, prenom, sexe;
    private String service, mat;
    private String dure, date;
    
    private int i; //un indice de déplacement des boutons "suivant / précédent / premier / dernier"
            
    Connection con = null; //variable qui permet de nous donner la possiblité de la connexion entre l'application et la base de données
    Statement st = null; //pour enregistrer nos requete mysql ainsi de les exécuter
    ResultSet rs = null; //pour enregistrer les résultats des requets mysql 
    private Object JoptionPane;
    
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        
        txtdate.setEnabled(false); //on ne peut pas changer le contenu du champs nommée txtdate de la date
        date(); //appel de la méthode date qui affiche la date système au démarrage de l'application
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbg = new javax.swing.ButtonGroup();
        id_label = new javax.swing.JLabel();
        mat_label = new javax.swing.JLabel();
        nom_label = new javax.swing.JLabel();
        prenom_label = new javax.swing.JLabel();
        service_label = new javax.swing.JLabel();
        duree_stage_label = new javax.swing.JLabel();
        sexe_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        txtdate = new javax.swing.JFormattedTextField();
        txtid = new javax.swing.JTextField();
        txtmat = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtduree = new javax.swing.JTextField();
        combservice = new javax.swing.JComboBox();
        jrb1 = new javax.swing.JCheckBox();
        jrb2 = new javax.swing.JCheckBox();
        jrb3 = new javax.swing.JCheckBox();
        btnpremier = new javax.swing.JButton();
        btnprecedent = new javax.swing.JButton();
        btnsuivant = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();
        btnn1 = new javax.swing.JButton();
        btnn3 = new javax.swing.JButton();
        btnn2 = new javax.swing.JButton();
        btnn4 = new javax.swing.JButton();
        jScrollPane1_tblstg = new javax.swing.JScrollPane();
        tblstg = new javax.swing.JTable();
        recherche_label = new javax.swing.JLabel();
        comborech = new javax.swing.JComboBox();
        txtrech = new javax.swing.JTextField();
        btnn5 = new javax.swing.JButton();
        fond_ecran_label = new javax.swing.JLabel();
        barre_tache = new javax.swing.JMenuBar();
        menu_deplacement = new javax.swing.JMenu();
        premier_dep = new javax.swing.JMenuItem();
        suivant_dep = new javax.swing.JMenuItem();
        dernier_dep = new javax.swing.JMenuItem();
        precedent_dep = new javax.swing.JMenuItem();
        aide = new javax.swing.JMenu();
        realis_par = new javax.swing.JMenuItem();
        quitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        id_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id_label.setText("Id : ");
        getContentPane().add(id_label);
        id_label.setBounds(70, 100, 29, 30);

        mat_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mat_label.setText("Mat : ");
        getContentPane().add(mat_label);
        mat_label.setBounds(70, 140, 39, 30);

        nom_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nom_label.setText("Nom : ");
        getContentPane().add(nom_label);
        nom_label.setBounds(70, 180, 46, 30);

        prenom_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prenom_label.setText("Prenom : ");
        getContentPane().add(prenom_label);
        prenom_label.setBounds(70, 220, 67, 30);

        service_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        service_label.setText("Service : ");
        getContentPane().add(service_label);
        service_label.setBounds(70, 260, 62, 30);

        duree_stage_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        duree_stage_label.setText("Durée_stage : ");
        getContentPane().add(duree_stage_label);
        duree_stage_label.setBounds(70, 300, 101, 30);

        sexe_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sexe_label.setText("Sexe : ");
        getContentPane().add(sexe_label);
        sexe_label.setBounds(70, 350, 46, 20);

        date_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date_label.setText("Date : ");
        getContentPane().add(date_label);
        date_label.setBounds(620, 340, 50, 30);

        txtdate.setBackground(new java.awt.Color(102, 255, 102));
        try {
            txtdate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtdate);
        txtdate.setBounds(720, 340, 170, 30);

        txtid.setBackground(new java.awt.Color(102, 255, 102));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtid);
        txtid.setBounds(220, 100, 170, 30);

        txtmat.setBackground(new java.awt.Color(102, 255, 102));
        txtmat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtmat);
        txtmat.setBounds(220, 140, 170, 30);

        txtnom.setBackground(new java.awt.Color(102, 255, 102));
        txtnom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtnom);
        txtnom.setBounds(220, 180, 170, 30);

        txtprenom.setBackground(new java.awt.Color(102, 255, 102));
        txtprenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtprenom);
        txtprenom.setBounds(220, 220, 170, 30);

        txtduree.setBackground(new java.awt.Color(102, 255, 102));
        txtduree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtduree);
        txtduree.setBounds(220, 300, 170, 30);

        combservice.setBackground(new java.awt.Color(102, 255, 51));
        combservice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combservice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Informatique", "Gestion et Recrutement", "Maintenance", "Logistique", "Fiscale ", "Transport" }));
        getContentPane().add(combservice);
        combservice.setBounds(220, 260, 170, 30);

        jrb1.setText("Masculin");
        jrb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jrb1);
        jrb1.setBounds(220, 350, 80, 20);

        jrb2.setText("Féminin");
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jrb2);
        jrb2.setBounds(300, 350, 80, 20);

        jrb3.setText("Autre");
        jrb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb3ActionPerformed(evt);
            }
        });
        getContentPane().add(jrb3);
        jrb3.setBounds(380, 350, 53, 20);

        btnpremier.setBackground(new java.awt.Color(102, 255, 102));
        btnpremier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpremier.setText("Premier");
        btnpremier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpremierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpremierMouseExited(evt);
            }
        });
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });
        getContentPane().add(btnpremier);
        btnpremier.setBounds(70, 390, 100, 60);

        btnprecedent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnprecedent.setText("Précédent");
        btnprecedent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnprecedentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnprecedentMouseExited(evt);
            }
        });
        btnprecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecedentActionPerformed(evt);
            }
        });
        getContentPane().add(btnprecedent);
        btnprecedent.setBounds(190, 390, 103, 60);

        btnsuivant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsuivant.setText("Suivant");
        btnsuivant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsuivantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsuivantMouseExited(evt);
            }
        });
        btnsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivantActionPerformed(evt);
            }
        });
        getContentPane().add(btnsuivant);
        btnsuivant.setBounds(310, 390, 100, 60);

        btndernier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndernier.setText("Dernier");
        btndernier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndernierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndernierMouseExited(evt);
            }
        });
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });
        getContentPane().add(btndernier);
        btndernier.setBounds(430, 390, 100, 60);

        btnn1.setBackground(new java.awt.Color(102, 255, 102));
        btnn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\medam\\Desktop\\Application Gestion Stagiaires\\icones\\ajouter.png")); // NOI18N
        btnn1.setText("Ajouter");
        btnn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn1MouseExited(evt);
            }
        });
        btnn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn1);
        btnn1.setBounds(70, 470, 140, 50);

        btnn3.setBackground(new java.awt.Color(102, 255, 102));
        btnn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnn3.setIcon(new javax.swing.ImageIcon("C:\\Users\\medam\\Desktop\\Application Gestion Stagiaires\\icones\\supprimer.png")); // NOI18N
        btnn3.setText("Supprimer");
        btnn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn3MouseExited(evt);
            }
        });
        btnn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn3);
        btnn3.setBounds(70, 530, 140, 50);

        btnn2.setBackground(new java.awt.Color(102, 255, 102));
        btnn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnn2.setIcon(new javax.swing.ImageIcon("C:\\Users\\medam\\Desktop\\Application Gestion Stagiaires\\icones\\modifier.png")); // NOI18N
        btnn2.setText("Modifier");
        btnn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn2MouseExited(evt);
            }
        });
        btnn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn2);
        btnn2.setBounds(220, 470, 140, 50);

        btnn4.setBackground(new java.awt.Color(102, 255, 102));
        btnn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnn4.setIcon(new javax.swing.ImageIcon("C:\\Users\\medam\\Desktop\\Application Gestion Stagiaires\\icones\\actualiser .png")); // NOI18N
        btnn4.setText("Actualiser");
        btnn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn4MouseExited(evt);
            }
        });
        btnn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn4);
        btnn4.setBounds(220, 530, 140, 50);

        tblstg.setBackground(new java.awt.Color(102, 255, 102));
        tblstg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblstg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstgMouseClicked(evt);
            }
        });
        jScrollPane1_tblstg.setViewportView(tblstg);

        getContentPane().add(jScrollPane1_tblstg);
        jScrollPane1_tblstg.setBounds(420, 100, 650, 230);

        recherche_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recherche_label.setText("Recherche par : ");
        getContentPane().add(recherche_label);
        recherche_label.setBounds(470, 480, 120, 20);

        comborech.setBackground(new java.awt.Color(102, 255, 102));
        comborech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comborech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id ", "Mat ", "Nom", "Prenom", "Service", "Duree_de_Stage", "Sexe", "Date" }));
        getContentPane().add(comborech);
        comborech.setBounds(650, 440, 170, 30);

        txtrech.setBackground(new java.awt.Color(153, 255, 102));
        txtrech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtrech);
        txtrech.setBounds(650, 520, 170, 30);

        btnn5.setBackground(new java.awt.Color(102, 255, 102));
        btnn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnn5.setIcon(new javax.swing.ImageIcon("C:\\Users\\medam\\Desktop\\Application Gestion Stagiaires\\icones\\rechercher.png")); // NOI18N
        btnn5.setText("Recherche");
        btnn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn5MouseExited(evt);
            }
        });
        btnn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn5);
        btnn5.setBounds(860, 460, 140, 60);

        fond_ecran_label.setBackground(new java.awt.Color(102, 255, 102));
        fond_ecran_label.setIcon(new javax.swing.ImageIcon("C:\\Users\\medam\\Desktop\\Application Gestion Stagiaires\\icones\\tophapp stage.jpg")); // NOI18N
        fond_ecran_label.setText("jLabel9");
        getContentPane().add(fond_ecran_label);
        fond_ecran_label.setBounds(0, -30, 1110, 720);

        menu_deplacement.setText("Déplacement");
        menu_deplacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deplacementActionPerformed(evt);
            }
        });

        premier_dep.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_UP, java.awt.event.InputEvent.ALT_MASK));
        premier_dep.setText("Premier");
        premier_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premier_depActionPerformed(evt);
            }
        });
        menu_deplacement.add(premier_dep);

        suivant_dep.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.ALT_MASK));
        suivant_dep.setText("Suivant");
        suivant_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suivant_depActionPerformed(evt);
            }
        });
        menu_deplacement.add(suivant_dep);

        dernier_dep.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DOWN, java.awt.event.InputEvent.ALT_MASK));
        dernier_dep.setText("Dernier");
        dernier_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dernier_depActionPerformed(evt);
            }
        });
        menu_deplacement.add(dernier_dep);

        precedent_dep.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        precedent_dep.setText("Précédent");
        precedent_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedent_depActionPerformed(evt);
            }
        });
        menu_deplacement.add(precedent_dep);

        barre_tache.add(menu_deplacement);

        aide.setText("Aide");

        realis_par.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        realis_par.setText("Réaliser par");
        realis_par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realis_parActionPerformed(evt);
            }
        });
        aide.add(realis_par);

        quitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        aide.add(quitter);

        barre_tache.add(aide);

        setJMenuBar(barre_tache);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb1ActionPerformed
        sexe = jrb1.getText(); //récupere le texte du sexe                // TODO add your handling code here:
    }//GEN-LAST:event_jrb1ActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
        sexe = jrb2.getText(); //récupere le texte du sexe             // TODO add your handling code here:
    }//GEN-LAST:event_jrb2ActionPerformed

    private void jrb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb3ActionPerformed
        sexe = jrb3.getText(); //récupere le texte du sexe             // TODO add your handling code here:
    }//GEN-LAST:event_jrb3ActionPerformed

    private void btnn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn1MouseEntered
        btnn1.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn1MouseEntered

    private void btnn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn1MouseExited
        btnn1.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn1MouseExited

    private void btnn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn2MouseEntered
        btnn2.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn2MouseEntered

    private void btnn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn2MouseExited
        btnn2.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn2MouseExited

    private void btnn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn3MouseEntered
        btnn3.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn3MouseEntered

    private void btnn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn3MouseExited
        btnn3.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn3MouseExited

    private void btnn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn4MouseEntered
        btnn4.setBackground(new java.awt.Color(255,255,255)); // TODO add your handling code here:
    }//GEN-LAST:event_btnn4MouseEntered

    private void btnn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn4MouseExited
        btnn4.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn4MouseExited

    private void btnn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn5MouseEntered
        btnn5.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn5MouseEntered

    private void btnn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn5MouseExited
        btnn5.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn5MouseExited

                                      
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Image imgico = ImageIO.read(getClass().getResource("stage.png"));
            this.setIconImage(imgico);
            this.setLocationRelativeTo(null);
                    
                    } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
          // connexion avec base de donnée stg1
          Class.forName("com.mysql.jdbc.Driver"); //forName est une méthode qui permet d'établir la connexion avec la base de données
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stg1","root",""); //connexion au bd avec l'utilisateur root et le mdp vide
          st = con.createStatement(); //creation des Statement
     
          jrbg.add(jrb1); //groupe de checkbox
          jrbg.add(jrb2); //groupe de checkbox
          jrbg.add(jrb3); //groupe de checkbox
          
          dt = new DefaultTableModel(); //dt c'est un variable pour stocké les element d'un tableau {ligne et colomn}(instance)
      
          dt.addColumn("id"); //ajouter les colonnes dans la variable d'instance dt sous forme de matrice
          dt.addColumn("matricule");
          dt.addColumn("nom");
          dt.addColumn("prenom");
          dt.addColumn("service");
          dt.addColumn("duree");
          dt.addColumn("sexe");
          dt.addColumn("date");
        
          tblstg.setModel(dt); //pour faire les traitements d'attributions des noms de columns de dt pour un tableau nommée tblstg
        
          Afficher(); //afficehr la liste des stagiaires
        
          i = 0;
          Deplacer(i); //remplir les champs 
        
        }catch(Exception e){
          System.out.printf("erreur   "+e.getMessage()); //getMessage c'est une fonction  pour afficher l'Erreur ou se trouve ?!!!!!
          JOptionPane.showMessageDialog(null, "Erreur de connexion\n  "+ e.getMessage());
        }
        // TODO add your handling code here:        // TODO add your handling code here:
    }                                 
//GEN-LAST:event_formWindowOpened
    
    //          Ajouter stg                                                
    private void btnn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn1ActionPerformed
        try{
            String sql = "INSERT INTO stagiaire  (matricule,nom,prenom,service,duree_de_stage,sexe,date)VALUES (?,?,?,?,?,?,?)"; //sql est une variable de type chaine pour stocker la requete
            PreparedStatement ps = con.prepareStatement(sql); //pour préparer la requete sql déclarée précédement
            
            ps.setString(1, txtmat.getText()); //value 1 contient mat , value 2 contient nom ....
            ps.setString(2, txtnom.getText());
            ps.setString(3, txtprenom.getText());
            ps.setString(4, combservice.getSelectedItem().toString());
            ps.setString(5, txtduree.getText());
            ps.setString(6, sexe);
            ps.setString(7, txtdate.getText());
            
            ps.executeUpdate(); // pour faire la mise à jour de ps qui contient les attributs matricule, nom ...
            Afficher(); // recharger la liste des stagiaires
            
            JOptionPane.showMessageDialog(null, "Stagiaire est ajouté");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur d'ajouter le stagiaire \n"+e.getMessage());
            System.err.println(""+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnn1ActionPerformed
                                              
    
    //          MODIFIER stg                                                
    private void btnn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn2ActionPerformed
        try{ 
            // msg d confirmation ! //Confirmer la modification ????? est le msg de l'alert et Modification !!!!! est le nom de l'alert
            if (JOptionPane.showConfirmDialog(null, "Confirmer la modification ?????", "Modification !!!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
                // on fait la mise à jour des données
               st.executeUpdate("UPDATE stagiaire SET matricule='"+txtid.getText()+"',nom='"+txtnom.getText()+"',prenom='"+txtprenom.getText()+"',service='"+combservice.getSelectedItem().toString()+"',duree_de_stage='"+txtduree.getText()+"',sexe='"+sexe+"',date='"+txtdate.getText()+"' WHERE id = "+ txtid.getText());       
               //lorseque en fait +txtfield.gettext+ en doit ecrit les appostrophe ""
  
               Afficher(); // recharger la liste des stagiaires
            }
        }catch(Exception e){
               JOptionPane.showMessageDialog(null, "Erreur de modification le stagiaire\n"+e.getMessage());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnn2ActionPerformed
                                               
    
    //          supprimer stg                                                 
    private void btnn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn3ActionPerformed
        try{
            //Suppression !!! est le nom de l'alert et "Attention !!!!!" + " tu veux supprimer ce stagaire" c'est le message de l'alert
            if(JOptionPane.showConfirmDialog(null, "Attention !!!!!" + " tu veux supprimer ce stagaire", "Suppression !!!",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
              //si textfield id est vide ,on peux pas supprimmer
              // on peut supprimer le stagiaire à travers son id 
              st.executeUpdate("Delete from stagiaire where id = "+ txtid.getText());
              Afficher(); // recharger la liste des stagiaires ...
            }
        }catch(Exception e){
              JOptionPane.showMessageDialog(null, "Erreur de suppression de stagiaire !\n"+e.getMessage());
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btnn3ActionPerformed
                                                
    
    private void btnn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn4ActionPerformed
        actualiser();
        Afficher();// TODO add your handling code here:
    }//GEN-LAST:event_btnn4ActionPerformed

    //recherche stagiaire                                                
    private void btnn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn5ActionPerformed
        try{ 
            dt.setRowCount(0); //pour vider tableau 
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery( "SELECT * FROM stagiaire WHERE "+combo()+"  like '%"+txtrech.getText()+"%'" );
    
            while(rs.next()){
               id = rs.getInt(1); //on peut écrire 1 ou id ...  
               mat = rs.getString("matricule"); // la même chose
               nom = rs.getString(3);
               prenom = rs.getString(4);
               service = rs.getString(5);
               dure = rs.getString(6);
               sexe = rs.getString(7);
               date = rs.getString(8);
            
               Object[] stg = {id,mat,nom,prenom,service,dure,sexe,date}; // creation d'objet nommée stg contient la ligne des infos suivantes 
               dt.addRow(stg); // il va l'ajouter dans la ligne de dt 
            }
     
            if (dt.getRowCount() == 0){ // s'il n'y a pas des enregistrements dans dt
               JOptionPane.showMessageDialog(null, "Aucun Stagiaire");
               Afficher(); // afficehr tout les stgs
            }else{
               i = 0;
               Deplacer(i); // sinon elle permet de déplacer dans le 1ere stagiare si i = 0
            }
    
        }catch (Exception m){
            JOptionPane.showMessageDialog(null, ""+m.getMessage());
            System.err.println(m); // System.err.println(m) : elle affiche l'erreur toujours en rouge 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnn5ActionPerformed
                                                 
    
    //          selectionnéé stg                                             
    private void tblstgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstgMouseClicked
        try{
           i = tblstg.getSelectedRow(); // getSelectedRow() fonction nous retourne le ligne selectionner par l'utilisateur
         
           Deplacer(i);
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Erreur de stagiaire selectionnée \n"+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblstgMouseClicked

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        premier();        // TODO add your handling code here:
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnprecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecedentActionPerformed
        precedent();   // TODO add your handling code here:
    }//GEN-LAST:event_btnprecedentActionPerformed

    private void btnsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivantActionPerformed
        suivant();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsuivantActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        dernier();        // TODO add your handling code here:
    }//GEN-LAST:event_btndernierActionPerformed

    private void btnpremierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpremierMouseEntered
        btnpremier.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnpremierMouseEntered

    private void btnpremierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpremierMouseExited
        btnpremier.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnpremierMouseExited

    private void btnprecedentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprecedentMouseEntered
        btnprecedent.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnprecedentMouseEntered

    private void btnprecedentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprecedentMouseExited
        btnprecedent.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnprecedentMouseExited

    private void btnsuivantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsuivantMouseEntered
        btnsuivant.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnsuivantMouseEntered

    private void btnsuivantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsuivantMouseExited
        btnsuivant.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnsuivantMouseExited

    private void btndernierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndernierMouseEntered
        btndernier.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btndernierMouseEntered

    private void btndernierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndernierMouseExited
        btndernier.setBackground(new java.awt.Color(102,255,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btndernierMouseExited

    private void premier_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premier_depActionPerformed
        premier();        // TODO add your handling code here:
    }//GEN-LAST:event_premier_depActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        dispose(); //pour faire sortir d'un emplacement        // TODO add your handling code here:
    }//GEN-LAST:event_quitterActionPerformed

    private void realis_parActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realis_parActionPerformed
        Réalisation r = new Réalisation(); //Réalisation() le nom de la classe
        r.setVisible(true); // rendre la visiblité de la réalisation
        // TODO add your handling code here:
    }//GEN-LAST:event_realis_parActionPerformed

    private void menu_deplacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deplacementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_deplacementActionPerformed

    private void suivant_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suivant_depActionPerformed
        suivant();        // TODO add your handling code here:
    }//GEN-LAST:event_suivant_depActionPerformed

    private void dernier_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dernier_depActionPerformed
        dernier();        // TODO add your handling code here:
    }//GEN-LAST:event_dernier_depActionPerformed

    private void precedent_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precedent_depActionPerformed
        precedent();        // TODO add your handling code here:
    }//GEN-LAST:event_precedent_depActionPerformed
                                        
    
    public String combo(){
        switch(comborech.getSelectedIndex()){ // comborech.getSelectedIndex()permet de donner l'indice (0,1,2...)
            case 0: return "id"; 
            case 1: return "matricule";
            case 2: return "nom";
            case 3: return "prenom";
            case 4: return "service";
            case 5: return "duree_de_stage";
            case 6: return "sexe";
            case 7: return "date";
        }
      return ""; //sinon il retourne null
    }
    
    //          procedure qui Afficher la liste des Stagiaire.
    private void Afficher(){
  
       txtid.setEnabled(false); // txtid est le nom du champ id de l'interface et setEnabled(false) est tu n'a pas le droit de modifier et d'accéder et d'écrire
   
       try{
          dt.setRowCount(0); // vider la list des stagiaires.
          rs = st.executeQuery("Select * From stagiaire"); // executeQuery est une méthode de Statement qui permet d'exécuter des requetes mysql et retourner le résultat de cette requette dans la variable rs(=result)
          
          while(rs.next()){
            id = rs.getInt("id"); // récupere l'id dans une variable id et l'autre comme ceci...
            mat = rs.getString("matricule");
            nom = rs.getString("nom");
            prenom = rs.getString("prenom");
            service = rs.getString("service");
            dure = rs.getString("duree_de_stage");
            sexe = rs.getString("sexe");
            date = rs.getString("date");
            
            Object[] t = {id,mat,nom,prenom,service,dure,sexe,date}; // un objet de type ligne nommée "t" contient les infos de stagiaire
            dt.addRow(t); // addRow est une méthode qui permet d'ajouter les infos de "t" sous forme de ligne de table "tblstg" de l'interface
         }
          
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Erreur afficher la liste des stagiaires \n"+e.getMessage());
        }
       
    }
    
    private void Deplacer(int i){
       try{
            if (dt.getRowCount() == 0){ //si il y aucun enregistrement tableau est vide
              btnpremier.setEnabled(false); //uncklickable
              btndernier.setEnabled(false); //uncklickable
              actualiser();
            }else{
              if(i == 0){ //si i est localiser sur le premier enregistrement  
                btnprecedent.setEnabled(false); //uncklickable
                btnsuivant.setEnabled(true); //cklickable
              }else if (i == dt.getRowCount()-1){ //  si i est localisé sur  dernier enregistrement
                btnprecedent.setEnabled(true); //cklickable
                btnsuivant.setEnabled(false); //uncklickable
              }else{ //si i est localisée dans la moitiée du tableau, ils sont activées
                btnprecedent.setEnabled(true); //cklickable
                btnsuivant.setEnabled(true); //cklickable
              }
            if(dt.getRowCount() == 1){//si il y a un seul enregistrement, nous avons un seul ligne
                btnprecedent.setEnabled(false); //uncklickable
                btnsuivant.setEnabled(false); //uncklickable
                btnpremier.setEnabled(false); //uncklickable
                btndernier.setEnabled(false); //uncklickable
            }else{
                btnpremier.setEnabled(true); //cklickable
                btndernier.setEnabled(true); //cklickable
            }
        }
                //id=0, mat=1, nom=2 .....
          txtid.setText(dt.getValueAt(i, 0).toString()); //il prend sa valeur "txtid" de dt dont la valeur est située dans l'indice i de ligne et 0 represente le num de ligne de tab qui contient id
          txtmat.setText(dt.getValueAt(i, 1).toString()); // i represente numero d ligne ,et 0 1 .. colonne
          txtnom.setText(dt.getValueAt(i, 2).toString()); // lorseque i=1 getValueAt nous retourne le premier ligne si i=2 le ligne ......
          txtprenom.setText(dt.getValueAt(i, 3).toString());
          combservice.setSelectedItem(dt.getValueAt(i, 4).toString());
          txtduree.setText(dt.getValueAt(i, 5).toString());
          
          String s = dt.getValueAt(i, 6).toString(); // représente tous les éléments de sexe dans le IF qui le suit
          if(s.equals("Masculin")){
              jrb1.setSelected(true);
          }else if(s.equals("Féminin")){
              jrb2.setSelected(true);
          }else{
              jrb3.setSelected(true);
          }
          
          //txtdate.setText(dt.getValueAt(i, 7).toString());
          
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Erreur de déplacement de stagiaire \n"+e.getMessage());
        }
    }
    
    public void actualiser(){ // fonction de type void ne retourne rien !!!!!!??
        txtid.setText(""); //permet d'actualiser les champs de l'interface par vider le contenu de chaque zone de texte de chaque attribut
        txtnom.setText("");
        txtprenom.setText("");
        combservice.setSelectedItem(1);
        jrb3.isSelected();
        txtduree.setText("");
        txtdate.setText("");
    }
    
    public void date(){ //pour récupérer la date système
      Date s = new Date(); //la variable s de type date contient la date système
      SimpleDateFormat d = new SimpleDateFormat("dd/MM/YYYY"); // d contient le format d'affichage de la date 
      txtdate.setText(d.format(s)); //affichage de format de date dans le champs txtdate de la date dans l'interface
    }
    
    public void premier(){
        try{
            i = 0; //le premier est de position 0
            Deplacer(i); // on le déplace dans la position i
        }catch(Exception e){
            ((JOptionPane) JoptionPane).showMessageDialog(null, "Erreur de premier stagiaire!\n"+e.getMessage());
        }
    
    }
    
    public void precedent(){
        try{
            i--; //désincrementation
            Deplacer(i); // ou Deplacer(--i); // et on le déplace dans la position i
        }catch(Exception e){
            ((JOptionPane) JoptionPane).showMessageDialog(null, "Erreur de precedent stagiaire!\n"+e.getMessage());
        }
    
    }
    
    public void suivant(){ //sans type de retour
       try{
            i++; //incrementation
            Deplacer(i); // ou Deplacer(++i); // et on le déplace dans la position i
        }catch(Exception e){
            ((JOptionPane) JoptionPane).showMessageDialog(null, "Erreur de suivant stagiaire!\n"+e.getMessage());
        } 
    }
    
    public void dernier(){
        try{
            i = dt.getRowCount() - 1; //contient le nombre de column - 1(on élimine 0 et on commence par 1,2 ... au lieu de 0,1,2 ...), il localise dans le dernier enregistrement
            Deplacer(i); // on le déplace dans la position i
        }catch(Exception e){
            ((JOptionPane) JoptionPane).showMessageDialog(null, "Erreur de dernier stagiaire!\n"+e.getMessage());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aide;
    private javax.swing.JMenuBar barre_tache;
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnn1;
    private javax.swing.JButton btnn2;
    private javax.swing.JButton btnn3;
    private javax.swing.JButton btnn4;
    private javax.swing.JButton btnn5;
    private javax.swing.JButton btnprecedent;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuivant;
    private javax.swing.JComboBox comborech;
    private javax.swing.JComboBox combservice;
    private javax.swing.JLabel date_label;
    private javax.swing.JMenuItem dernier_dep;
    private javax.swing.JLabel duree_stage_label;
    private javax.swing.JLabel fond_ecran_label;
    private javax.swing.JLabel id_label;
    private javax.swing.JScrollPane jScrollPane1_tblstg;
    private javax.swing.JCheckBox jrb1;
    private javax.swing.JCheckBox jrb2;
    private javax.swing.JCheckBox jrb3;
    private javax.swing.ButtonGroup jrbg;
    private javax.swing.JLabel mat_label;
    private javax.swing.JMenu menu_deplacement;
    private javax.swing.JLabel nom_label;
    private javax.swing.JMenuItem precedent_dep;
    private javax.swing.JMenuItem premier_dep;
    private javax.swing.JLabel prenom_label;
    private javax.swing.JMenuItem quitter;
    private javax.swing.JMenuItem realis_par;
    private javax.swing.JLabel recherche_label;
    private javax.swing.JLabel service_label;
    private javax.swing.JLabel sexe_label;
    private javax.swing.JMenuItem suivant_dep;
    private javax.swing.JTable tblstg;
    private javax.swing.JFormattedTextField txtdate;
    private javax.swing.JTextField txtduree;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
}
